lb:
  image: mblouin/eea.docker.haproxy
  ports:
    - "80:80"
    - "1936:1936"
  links:
    - web
web:
  build: web
  ports:
    - "80"
  links:
    - rest
rest:
  build: java
  ports:
    - "8080:8080"
load_test:
  build: load_test
  links:
    - lb:web
