lb:
  image: mblouin/eea.docker.haproxy
  ports:
    - "80:80"
    - "1936:1936"
  links:
    - web
  environment:
    - SERVICE_NAMES=azuredevtestdeploy_web
web:
  build: web
  ports:
    - "80"
  links:
    - rest
  volumes:
    - ./web/prefork.conf:/etc/apache2/conf-enabled/prefork.conf
rest:
  build: java
  ports:
    - "8080:8080"
load_test:
  build: load_test
  links:
    - lb:web
  volumes:
    - ./load_test/tests:/tests
